tasks:
  - init: >
      language-server/gradlew -p language-server/ build &&
      yarn --cwd webview && 
      yarn --cwd extension
  - command: gp open workspace/MrsGrantsSecretCompartment.sm 
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false
    addLabel: false

vscode:
  extensions:
    - TypeFox.vscode-xtext-sprotty-example@0.0.2:aOidRVFz2O+NaT2Slwxlzg==
